
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DENABLE_PTHREAD_MUTEX_ERRORTYPE")	# for test purpose
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DENABLE_BACKTRACE_LOGOUTPUT")      # for test purpose
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DENABLE_DEBUG_LOGOUTPUT")      # for test purpose
